Added rules to workflow

diff --git a/.github/workflows/develop-to-master.yaml b/.github/workflows/develop-to-master.yaml
--- a/.github/workflows/develop-to-master.yaml
+++ b/.github/workflows/develop-to-master.yaml
@@ -2,7 +2,7 @@ name: Enforce Merge from Develop
 
 on:
   pull_request:
-    branches: [master]  # Solo se activa para PRs que apunten a master
+    branches: [master]  # Only triggers for PRs targeting master
 
 jobs:
   check-branch:
@@ -11,5 +11,14 @@ jobs:
       - name: Verify source branch
         if: github.head_ref != 'develop'
         run: |
-          echo "Error: Merging into master is only permitted from the develop branch.."
+          echo "Error: Only merging to master from develop branch is allowed."
+          exit 1
+
+  check-assignee:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify assignment to owner
+        if: github.event.pull_request.user.login != github.repository_owner && !contains(github.event.pull_request.assignees.*.login, github.repository_owner)
+        run: |
+          echo "Error: The repository owner must be assigned to this PR."
           exit 1
